### ISSUE TITLE
CMake Error at CMakeLists.txt:31 (find_package):

### ISSUE THREAD

**Issue by acmLL** [Veridise/Vanguard#96]
This error occurred when I tried to build the docker image of the v1 branch

=> ERROR [48/68] RUN cmake -G "Unix Makefiles" ../                                                          6.6s
------
 > [48/68] RUN cmake -G "Unix Makefiles" ../:
#52 3.409 -- The C compiler identification is GNU 11.3.0
#52 3.868 -- The CXX compiler identification is GNU 11.3.0
#52 3.936 -- Detecting C compiler ABI info
#52 4.272 -- Detecting C compiler ABI info - done
#52 4.305 -- Check for working C compiler: /usr/bin/cc - skipped
#52 4.319 -- Detecting C compile features
#52 4.319 -- Detecting C compile features - done
#52 4.335 -- Detecting CXX compiler ABI info
#52 4.576 -- Detecting CXX compiler ABI info - done
#52 4.605 -- Check for working CXX compiler: /usr/bin/c++ - skipped
#52 4.607 -- Detecting CXX compile features
#52 4.609 -- Detecting CXX compile features - done
#52 4.667 -- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
#52 4.839 -- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.13") 
#52 4.951 -- Linker detection: GNU ld
#52 4.963 CMake Error at CMakeLists.txt:31 (find_package):
#52 4.963   Could not find a package configuration file provided by "SVF" (requested
#52 4.963   version 2.5) with any of the following names:
#52 4.963 
#52 4.963     SVFConfig.cmake
#52 4.963     svf-config.cmake
#52 4.963 
#52 4.963   Add the installation prefix of "SVF" to CMAKE_PREFIX_PATH or set "SVF_DIR"
#52 4.963   to a directory containing one of the above files.  If "SVF" provides a
#52 4.963   separate development package or SDK, be sure it has been installed.
#52 4.963 
#52 4.963 
#52 4.964 -- Configuring incomplete, errors occurred!
#52 4.964 See also "/vanguard/cmake-build-debug/CMakeFiles/CMakeOutput.log".
------
executor failed running [/bin/sh -c cmake -G "Unix Makefiles" ../]: exit code: 1

**Comment by Technius** [comment]
Hi @acmLL, what command did you run to compile the project?

**Comment by acmLL** [comment]
Hey, @Technius . I have visited the V1 branch and ran "docker build -t vanguard ." on my macos. Thanks!

**Comment by Technius** [comment]
The v1 branch does not have a `Dockerfile`; the image needs to be built with Nix. You could alternatively compile from source outside of Docker; see the [README](https://github.com/Veridise/Vanguard/tree/v1#how-to-install) for more information.

Regarding the Nix build, I believe there may be some problems with that though--the derivation we are building for `solc` is currently in one of our private repositories and may not be accessible to you (though we are planning to replace it with something public in the near future). A workaround is to pull the binaries from our `veridise-public` cache on cachix.
